name: MassTransit
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tests/MassTransit.Benchmark/Dockerfile
          platforms: linux/amd64
          push: false
