name: MassTransit
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            yhnujm/mtbenchmark
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: yhnujm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tests/MassTransit.Benchmark/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
